output_dir: 'experiments'  # Base directory for experiment outputs

data:
  data_dir: '/home/andrea/git/UCLA/UCLA_MATH156_Project/KingsCollege'
  train_file: 'dataset_train.txt'
  val_file: 'dataset_test.txt'  # Optional
  batch_size: 64
  num_workers: 4

model:
  type: 'models.ResNetCBAM'
  params:
    block_name: 'models.BasicBlockWithCBAM'
    layers: [2, 2, 2, 2]  # ResNet18-like
    pos_dim: 3
    orien_dim: 4

optimizer:
  type: 'Adam'
  params:
    lr: 1.0e-4

scheduler:  # Optional
  type: 'ReduceLROnPlateau'
  params:
    mode: 'min'
    factor: 0.5
    patience: 5
    min_lr: 1.0e-6

loss:
  type: 'utils.StaticLoss'
  params:
    beta: 3.0
    type: 'torch.nn.MSELoss'

epochs: 50
device: 'cuda'  # 'cuda' or 'cpu'